### ISSUE TITLE
Something's really wrong. They'll easily win.

### ISSUE THREAD

**Issue by kartikeypant** [felicity-buzz-2k16/quiz-portal-backend#1]
If you see, a person can easily win just by giving the correct answer to the first question multiple times. Aren't we missing something?

There must be some problem in this part of the code.

``` js
router.post('/check/:qno(\\d+)?', middleware.isAuthenticated, (req, res) => {
  var { qno } = req.params;
  const { answer } = req.body;
  const { lastQuestionAllowed } = req.user;
  if (!qno) qno = lastQuestionAllowed;
  if (qno > lastQuestionAllowed) {res.sendStatus(403); return false;}
  models.Question.findOne({where : { qno }})
    .then(question => {
      if (question) {
        if (question.answer == answer) req.user.update({lastQuestionAllowed: lastQuestionAllowed + 1});
        res.send({result: question.answer == answer});
      } else res.sendStatus(400);
    })
})
```

Someone please fix it.

**Comment by yash-iiith** [comment]
if the qno is less than lastquestionallowed and the person answers it correctly then also lastquestionallowed is incremented
so in the 2nd if statement if  "qno > lastquestionallowed" is replaced by "qno!=lastquestionallowed" it may solve the issue.

**Comment by kartikeypant** [comment]
You can't show an error message for giving answer to a question which the person has already solved. So, you need to give the condition somewhere else.

**Comment by meghprkh** [comment]
You are on track! ☺

But if you replace that statement then if I try to answer a previous
question I would get a 403. Not very acceptable right. I should be allowed
to answer a previous question. Instead try to put the condition near to
where we are actually incrementing lastQuestionAllowed

Regards,
Megh Parikh

**Comment by yash-iiith** [comment]
if (question.answer == answer) req.user.update({lastQuestionAllowed: lastQuestionAllowed + 1});
in this if condition if we && qno==lastquestionallowed
then it will be fine i guess

**Comment by kartikeypant** [comment]
Yes, you're right!

**Comment by meghprkh** [comment]
Yes. Great. Would be awesome if you could fork this repo and commit. Then
file a PR

Regards,
Megh Parikh

**Comment by meghprkh** [comment]
@kartikey You win again :p

Regards,
Megh Parikh

**Comment by kartikeypant** [comment]
@meghprkh Hahaha.. xD

**Comment by meghprkh** [comment]
@yash-iiith Thanks :+1:
