### ISSUE TITLE
Can anybody help me with this error? happens when i npm start backend

### ISSUE THREAD

**Issue by fireballpoint1** [felicity-buzz-2k16/quiz-portal-backend#15]
/home/mayankmodi/quiz-portal-backend/src/auth.js:20
        const { email, password } = req.body;
              ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/mayankmodi/quiz-portal-backend/src/index.js:20:21)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by anubhabsen** [comment]
delete contents of `db.sqlite`. If that doesn't solve the problem, delete your repo and re clone from here and do the same (assuming you haven't started working on some issue on your own in which case you need to upload your code somewhere)

**Comment by fireballpoint1** [comment]
i just re cloned didnt solve it 
doesnt that line 20 mean something?

**Comment by anubhabsen** [comment]
Looks like you have extra/ less brackets

**Comment by nikhilrayaprolu** [comment]
Try adding
'use strict' 
One the first line of the file

**Comment by fireballpoint1** [comment]
unexpected identifier

**Comment by fireballpoint1** [comment]
ok got that right shows the previous error again

**Comment by meghprkh** [comment]
Install node 6 usig nvm. How many times must I stress that node 6 is
needed? :/

Regards,
Megh Parikh

**Comment by anubhabsen** [comment]
I was just about to ask if readme was read :stuck_out_tongue:

**Comment by fireballpoint1** [comment]
![gitit](https://cloud.githubusercontent.com/assets/16238837/16896008/683c3d1e-4ba4-11e6-8441-db1ab1350cda.png)

**Comment by meghprkh** [comment]
Has been solved. closing (If you update your node version, you may have to run npm rebuild in the backend directory)
