### ISSUE TITLE
Scoring system

### ISSUE THREAD

**Issue by meghprkh** [felicity-buzz-2k16/quiz-portal-backend#2]
Hmmm... a scoring system seems a trivial feature, must not be so hard to implement. After all, what the scoring system does is if given a right answer add something to the score and if given a wrong answer deduct something from the score.

**Comment by anubhabsen** [comment]
Should there be a deduction too?

**Comment by pranavbhasin96** [comment]
I dont think there is deduction in the contests. Just addition on right answer

**Comment by meghprkh** [comment]
For adding flexibility I suggest you create a module `scoring.js` exporting the function `getNewScore (oldScore : int, isCorrect : bool)` (note that the type annotation is only for explanation)

**Comment by meghprkh** [comment]
Initially we dont want the score to be complex (dependent on the history of each question, as in for the first wrong answer deduct this much, then this much etc). We just want a score to be associated to each user. Maybe start by trying to edit the user model (present in `models/user.js`) and adding the score field. Sounds like we can add a score field to the user model and increment and decrement it properly when we are trying to check the answer of the question (we do this in `question.js`, `/check` route)

**Comment by meghprkh** [comment]
Properties of the score field:
- number (int will do)
- default 0
- allow null false
