### ISSUE TITLE
Scoreboard

### ISSUE THREAD

**Issue by meghprkh** [felicity-buzz-2k16/quiz-portal-backend#3]
Not that after fixing bug https://github.com/felicity-buzz-2k16/quiz-portal-backend/issues/2 we have the score associated with each user, would be nice if we could get the scoreboard

**Comment by pranavbhasin96** [comment]
How should we return all the names along with their corresponding scores? As an object?

**Comment by meghprkh** [comment]
An array of objects. I think totest sequelize queries, there is also a
sequelize CLI. But you can use the node repl to

Regards,
Megh Parikh

**Comment by pranavbhasin96** [comment]
Will this do?

``` javascript
models.User.findAll({
    attributes: ['name', 'score'],
    order : [ [ 'score','DESC'] ] })
    .then(//function to send data in response)
```

**Comment by pranavbhasin96** [comment]
Also i have a doubt that in what way will findAll return data from the database? Will it send the data as an array of object only?

**Comment by meghprkh** [comment]
yes to both

**Comment by pranavbhasin96** [comment]
I completed the functionality where it gives the score of all players in descending order. Now should there also be any other feature such as "You should be authenticated to see it" or any other thing?

**Comment by meghprkh** [comment]
Ni but there should be cache. But that will be in another. Will se e
tomorrow

Regards,
Megh Parikh
